# Site settings & data
title: Darshan Jogad
author: Darshan Jogad
description: Personal blog and resume
url: https://myurl.com/
avatar: eniac-woman.jpg
resume: "/static/sample-resume.pdf"
email: darshanmjogad@gmail.com
github: dmjogad
twitter: darshanjogad
linkedin: darshan-jogad-11a268168
instagram: darshanjogad__dj
google_analytics: UA-12345678-1
feed:
  subtitle: I wrote the book on electronic digital computing.
  filename: feed.xml
  path: "/feed/feed.xml"
  url: https://myurl.com/feed/feed.xml
  id: https://myurl.com/


# Build settings
markdown: kramdown
